import type { Metadata } from 'next';
import { Session } from 'next-auth';
import { Inter } from 'next/font/google';

import { SessionProvider } from '@/components/nextAuth/SessionProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
  session: Session | null | undefined,
) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-white`}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
